# Generated by Django 4.1.5 on 2023-01-18 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mv_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='movies',
            new_name='movie',
        ),
    ]
